apiVersion: v1
kind: Secret
metadata:
    name: postgres-passwd
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jEA6zxzQ9m96C6tZiV5F4Q==,iv:ZtOf9pigTcl5Fgm/1j8yl+7/zqBoYHVRC2YlNghgynQ=,tag:J8yWGb7eS/9T402fpMpLiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k95px4rxmgcmcqchydq9nrnd354t89pyw5rw66e4cg4chv2ywckscqtxr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMEY5MzN0OEVya0g2a3U2
            WlpNblprcHJnK1VObjlzdC9ubDZZR3E5RkhBClR3M2NIcnF0VFdMMExmNVNzcEsz
            cDBiOE1yS1FTcURlUUVQZDUvVU12ZGsKLS0tIFgxZXh0NGp1N2tJWHQ4VnFzOFUy
            bFZWMkpaSS9mYzNnazRpY2piVDlIcmcK2YXM45txqpZ5eKrhhpXTtl74rpeSsxAM
            yZMN9Orl1EVbv/wXcgSQ5xBZSKMLHLmXF1Raaqf9y87B7tv2oNHyjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T17:49:57Z"
    mac: ENC[AES256_GCM,data:bHDqEj9vgRA1zOw6KntQnbhXPk1W1+vqBuQXlKT0vfC2C34ADZmxzOD22MsRJwspJPfXRejpvS8F7rO95wrpvTB4H9x2+VCTyQo56n9QTbPijh0Rl9L+LRbS3uvMzVXxxYvT/4QemWJPnVkzrntPX8aK+wu2t6JbVA1V5AHGyeo=,iv:FhGRMVWVcBNkXHzTFvnzUA5+bcyHRufvjTwsecXvUUQ=,tag:FjGhfsJZpgLPbD9CnH55lg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
