apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 
  name: connecting-pods-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgen
  template:
    metadata:
      labels:
        size: verybig
        app: hashgen
    spec:
      containers:
        - name: hashgen
          image: pitrak13/hashgen:113
          envFrom:
          - configMapRef:
              name: config
      nodeSelector:
        networkquality:
