apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myspace
  name: connecting-pods-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgen
  template:
    metadata:
      labels:
        size: verybig
        app: hashgen
    spec:
      containers:
        - name: hashgen
          image: k3d-test-app-reg:5050/hashgen:112
      nodeSelector:
        networkquality: veryfast
