apiVersion: v1
kind: Service
metadata:
  namespace: 
  name: hashgen-svc
spec:
  type: NodePort
  selector:
    app: hashgen
  ports:
    - name: http
      port: 6578
      protocol: TCP
      targetPort: 7998
