apiVersion: apps/v1
kind: Deployment
metadata:
  name: persisting-data-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpongs
  template:
    metadata:
      labels:
        app: pingpongs
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: pingpong-status-claim
      containers:
        - name: hashgen
          image: k3d-test-app-reg:5050/hashgen:1.12
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/data
        - name: pingpong
          image: k3d-test-app-reg:5050/pingpong:1.12
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/data
