apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 
  name: stateful-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: pitrak13/pingpong:113
          envFrom:
            - secretRef:
                name: postgres-passwd
