apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: persisting-data-ing
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pingpong-svc
            port:
              number: 2345
      - path: /current-status
        pathType: Prefix
        backend:
          service:
            name: hashgen-svc
            port:
              number: 3456
