apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-gen-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgen-timestamp
  template:
    metadata:
      labels:
        app: hashgen-timestamp
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: pingpong-status-claim
      containers:
        - name: hashgen
          image: k3d-test-app-reg:5050/hashgen:test
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/data
        - name: timestamp
          image: k3d-test-app-reg:5050/timestamp:test1
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/data
